name: pybtls-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - scikit-build-core
  - wheel
  - pybind11
  - pytest
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pyarrow
  - nbsphinx
  - pip
  - pip:
    - pydata_sphinx_theme
    - sphinx_autodoc_typehints
