[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.10.0",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/tests/*.py"
test-skip = "*universal2:arm64"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests"
]
