name: CI

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: pytest (${{ matrix.os }}, py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        python: ['3.10', '3.11', '3.12', '3.13']  # Supported python versions

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      CMAKE_BUILD_PARALLEL_LEVEL: '3'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      # Optional cache to speed C/C++ rebuilds (kept lean)
      - name: Enable ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ci-${{ runner.os }}-py${{ matrix.python }}

      - name: Install package + test deps
        run: |
          python -m pip install -U pip
          pip install -e .[test]

      - name: Run tests
        run: pytest -q

  # Build sdist once on linux
  sdist-smoke:
    name: sdist smoke test (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build sdist
        run: |
          python -m pip install -U pip build
          python -m build --sdist
      - name: Install sdist into clean venv and import
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install dist/*.tar.gz
          python -c "import pybtls; print('pybtls version:', getattr(pybtls, '__version__', 'unknown'))"
