name: Conda

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - PyBTLS
  # pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9","3.10","3.11","3.12"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v3

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify

      - name: Build
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ python_example

      - name: Test
        run: python tests/test.py
