name: Conda Publish

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-conda:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        py: [3.9, 3.10, 3.11, 3.12, 3.13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          miniforge-variant: Mambaforge
          python-version: ${{ matrix.py }}

      - name: Install conda-build and tools
        shell: bash -l {0}
        run: |
          mamba install -y conda-build anaconda-client pip cmake make ninja
          conda config --set auto_update_conda false
          conda config --set report_errors false

      - name: Build conda package
        shell: bash -l {0}
        env:
          VERSION: ${{ github.event.release.tag_name || github.ref_name }}
        run: |
          echo "Using version: ${VERSION}"
          conda-build conda/recipe --output-folder conda-build --channel conda-forge --python ${{ matrix.py }}

      - name: Upload conda artifact
        uses: actions/upload-artifact@v4
        with:
          name: conda-${{ matrix.os }}-py${{ matrix.py }}
          path: conda-build/**/**/*.tar.bz2

  publish-conda:
    needs: build-conda
    runs-on: ubuntu-latest
    steps:
      - name: Download conda artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: conda-*
          path: conda-dist
          merge-multiple: true
      - name: Set up mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          miniforge-variant: Mambaforge
      - name: Upload to Anaconda.org
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          test -n "$ANACONDA_API_TOKEN" || { echo "Missing ANACONDA_API_TOKEN secret"; exit 1; }
          shopt -s globstar nullglob
          files=(conda-dist/**/*.tar.bz2)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No conda packages found to upload" >&2
            exit 1
          fi
          for f in "${files[@]}"; do
            echo "Uploading $f"
            anaconda upload --label main "$f"
          done