name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write  # For PyPI trusted publishing

jobs:
  build-ubuntu:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: ubuntu-latest
      build: "cp39-* cp310-* cp311-* cp312-*"
      test_extras: "test"
      test_command: "pytest -q {project}/tests"
      build_verbosity: "1"
      build_sdist: true

  build-windows:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: windows-latest
      build: "cp39-* cp310-* cp311-* cp312-*"
      test_extras: "test"
      test_command: "pytest -q {project}/tests"
      build_verbosity: "1"
      build_sdist: false

  build-macos-intel:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: macos-13
      build: "cp39-* cp310-* cp311-* cp312-*"
      test_extras: "test"
      test_command: "pytest -q {project}/tests"
      build_verbosity: "1"
      build_sdist: false

  build-macos-arm:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: macos-14
      build: "cp39-* cp310-* cp311-* cp312-*"
      test_extras: "test"
      test_command: "pytest -q {project}/tests"
      build_verbosity: "1"
      build_sdist: false

  publish:
    name: Publish to PyPI
    needs: [build-ubuntu, build-windows, build-macos-intel, build-macos-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.5
        with:
          skip-existing: true
          print-hash: true