name: Wheels on Release (publish)

on:
  release:
    types: [published]
  # push:
  #   tags:
  #     - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # PyPI Trusted Publishing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    uses: ./.github/workflows/_wheels-util.yml
    with:
      publish: true
      build_sdist: true
