name: Wheels

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HOST_PYTHON: "3.12"     # Single python runner
  CIBW_VERSION: "v2.21.3" # one pin, one place

jobs:
  wheels:
    name: Build wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # Note CPython versions specified in pyproject.toml

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.HOST_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.HOST_PYTHON }}

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@${{ env.CIBW_VERSION }}

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  sdist:
    name: Build sdist (once)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.HOST_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.HOST_PYTHON }}
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz