name: Wheels

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ubuntu:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: ubuntu-latest
      build_sdist: true

  build-windows:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: windows-latest
      build_sdist: false

  build-macos-intel:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: macos-13
      build_sdist: false

  build-macos-arm:
    uses: ./.github/workflows/_build_wheels_sdist.yml
    with:
      os: macos-14
      build_sdist: false
